# Generated by Django 4.1.4 on 2023-01-03 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_1', models.CharField(max_length=12)),
                ('telefono_2', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_inclusion', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
