# Generated by Django 4.1.4 on 2023-01-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_coments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='signature',
            field=models.CharField(default='firma', max_length=100),
        ),
    ]
