# Generated by Django 4.1.4 on 2023-01-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_coments_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coments',
            new_name='Comment',
        ),
    ]
